-- ==========================================================
-- Supabase Schema & Data Migration for 'public.categories'
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- ==========================================================

-- 1. Drop existing table if you want a clean reset, then create table
DROP TABLE IF EXISTS public.categories CASCADE;

CREATE TABLE public.categories (
  id serial NOT NULL,
  class_id integer NOT NULL,
  name character varying(100) NOT NULL,
  super_category character varying(50) NOT NULL,
  disposal_advice text[] NOT NULL,
  recycling_options text[] NULL,
  dos text[] NULL,
  donts text[] NULL,
  description text NULL,
  is_recyclable boolean NULL DEFAULT false,
  created_at timestamp with time zone NULL DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_class_id_key UNIQUE (class_id)
);

-- 2. Enable Row Level Security and allow public reads
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'categories' AND policyname = 'Allow public read access'
  ) THEN
    CREATE POLICY "Allow public read access" ON public.categories FOR SELECT USING (true);
  END IF;
END $$;

-- 3. Insert / Upsert all 59 categories
INSERT INTO public.categories (
  class_id,
  name,
  super_category,
  disposal_advice,
  recycling_options,
  dos,
  donts,
  description,
  is_recyclable
) VALUES
  (1, 'plastic bottle', 'plastic', ARRAY['Empty and rinse the bottle before disposal', 'Remove the cap and label if possible (often a different plastic type)', 'Crush or flatten the bottle to save space', 'Put it in the dry,recyclable waste bin, never in wet waste', 'Hand it to your local kabadiwala, scrap dealer, or municipal dry-waste centre']::text[], ARRAY['Sold by weight to local kabadiwalas,scrap dealers', 'Collected at Material Recovery Facilities (MRFs) run by municipal corporations', 'Processed by PET recyclers such as Ganesha Ecosphere and Banyan Nation', 'Digital marketplaces like Recykal connect households,bulk generators to registered recyclers under EPR', 'Recycled into polyester fibre, new bottles, straps, and fabric']::text[], ARRAY['Rinse out residue before storing for recycling', 'Flatten to reduce volume', 'Keep separate from wet,organic waste', 'Store caps separately if your local collector asks for it']::text[], ARRAY['Don''t reuse a single-use PET bottle indefinitely for drinking water (heat,sunlight exposure degrades it)', 'Don''t burn plastic bottles at home', 'Don''t mix with food waste or other contaminants', 'Don''t throw into drains or water bodies']::text[], 'PET (Polyethylene Terephthalate, resin code 1) bottles used for water, soft drinks, and oil. One of the most widely recycled plastics in India.', true),
  (2, 'plastic container', 'plastic', ARRAY['Empty out any food residue and rinse thoroughly', 'Check the recycling code (triangle number) on the base', 'Separate the lid if it''s a different plastic type', 'Place clean, dry containers in the dry-waste bin', 'Give to a local scrap dealer or municipal dry-waste collection point']::text[], ARRAY['Collected by kabadiwalas and sold to recyclers by resin type', 'Sorted at municipal MRFs for PP,HDPE reprocessing', 'Recycled into pellets, buckets, pipes, and other moulded plastic goods']::text[], ARRAY['Wash and dry before storing', 'Sort by plastic type where bins allow it', 'Flatten where possible']::text[], ARRAY['Don''t discard oily,greasy containers without cleaning first', 'Don''t burn or landfill without segregating', 'Don''t mix with e-waste or hazardous waste']::text[], 'Rigid plastic containers such as food boxes, tubs, and takeaway containers, usually PP (resin code 5) or HDPE (resin code 2). Recyclability depends on the resin.', true),
  (3, 'plastic cup', 'plastic', ARRAY['Empty out any liquid completely', 'Check whether it''s plastic (PP, recyclable) or polystyrene,thermocol (limited recycling)', 'Do not mix with wet waste even if slightly damp', 'Place clean cups in the dry-waste bin', 'Prefer reusable cups — single-use plastic,thermocol cups are restricted under national rules']::text[], ARRAY['PP cups collected by kabadiwalas,scrap dealers for reprocessing', 'Polystyrene cups routed to EPS recyclers or RDF,cement-kiln co-processing where mechanical recycling isn''t viable', 'Some urban local bodies run dry-waste collection centres accepting mixed plastics']::text[], ARRAY['Rinse before discarding', 'Store separately from soiled,wet items']::text[], ARRAY['Don''t use single-use plastic or thermocol cups — banned as single-use plastic nationwide since 1 July 2022', 'Don''t burn cups (releases toxic fumes)', 'Don''t litter or throw into water bodies']::text[], 'Disposable drinking cups made of PP, polystyrene, or plastic-coated paper. Plain plastic,polystyrene cups and glasses are on India''s banned single-use plastic list.', true),
  (4, 'plastic bag', 'plastic', ARRAY['Check thickness — anything below 120 microns is illegal to manufacture, sell, or use', 'Shake out and remove food,waste residue', 'Flatten and bundle several bags together', 'Keep separate from wet,organic waste', 'Hand over to dry-waste collection or a kabadiwala']::text[], ARRAY['Collected by local scrap dealers and municipal dry-waste centres', 'Recycled into granules used for bin liners, pipes, and other low-grade plastic goods', 'Some retail chains run bag take-back,collection drives under EPR']::text[], ARRAY['Reuse a bag as many times as possible before discarding', 'Keep clean and dry for recycling', 'Bundle bags together rather than disposing loose']::text[], ARRAY['Don''t use or accept bags thinner than 120 microns — banned nationally', 'Don''t burn plastic bags', 'Don''t dump in drains, rivers, or open land (a major cause of drain-choking and flooding)']::text[], 'Thin flexible carry bags, usually LDPE,HDPE. India mandates a minimum thickness of 120 microns (since 31 Dec 2022); thinner bags are banned nationwide.', true),
  (5, 'plastic wrapper', 'plastic', ARRAY['Empty out any food crumbs and shake clean', 'Do not mix with wet waste', 'Hand over to municipal dry-waste centres that accept MLP under EPR schemes', 'Look out for brand take-back,collection programmes']::text[], ARRAY['Co-processed as alternative fuel in cement kilns (mechanical recycling is limited)', 'Converted into Refuse Derived Fuel (RDF) for cement plants', 'Producer take-back drives, e.g. ITC''s MLP collection initiative that sorts and bales waste with local waste-picker networks before sending it to recyclers']::text[], ARRAY['Keep wrappers clean and dry', 'Store separately for special MLP collection drives', 'Support brand take-back,collection points where available']::text[], ARRAY['Don''t expect regular kabadiwalas to always accept MLP — many reject it as low value', 'Don''t burn openly (mixed layers release toxic emissions)', 'Don''t mix with single-polymer recyclables — it contaminates the batch']::text[], 'Multilayer plastic (MLP) wrappers — chip packets, snack,sweet wrappers — combine several thin plastic,foil layers, which makes them very hard to mechanically recycle.', false),
  (6, 'polythene', 'plastic', ARRAY['Check thickness — anything below 120 microns is illegal nationwide', 'Clean and dry before disposal', 'Segregate into dry waste', 'Hand to a kabadiwala or dry-waste collection centre', 'Report illegal thin-polythene sale to your local municipal,pollution control authority']::text[], ARRAY['Local recyclers process compliant polythene into granules for low-grade plastic products', 'Many municipal corporations run door-to-door dry-waste collection']::text[], ARRAY['Reuse before discarding', 'Keep separate from biodegradable waste']::text[], ARRAY['Don''t manufacture, sell, or use polythene bags below 120 microns — banned nationally', 'Don''t burn polythene', 'Don''t dump into water bodies or drains']::text[], 'Thin polyethylene sheeting,bags used for packaging and carrying. Tightly restricted in India due to littering and drain-blockage problems.', true),
  (7, 'styrofoam', 'plastic', ARRAY['Don''t crush or crumble unnecessarily — this creates hard-to-collect micro-beads', 'Keep dry and free of food contamination', 'Hand it to a dedicated EPS,thermocol recycler if one operates in your city', 'Otherwise dispose of via municipal dry-waste collection, never with wet,general waste']::text[], ARRAY['Specialised EPS recyclers (e.g., Thermowaste Solutions in Delhi-NCR) melt thermocol into lumps and extrude it into granules for reuse', 'Where no EPS recycler exists, sent for RDF,cement-kiln co-processing']::text[], ARRAY['Keep separate from wet,food waste', 'Store flat,whole where possible for easier bulk collection']::text[], ARRAY['Don''t use thermocol decorations, plates, or cups — banned as single-use plastic nationwide since 1 July 2022', 'Don''t burn thermocol (releases highly toxic fumes)', 'Don''t break it into small pieces — it scatters and pollutes further']::text[], 'Expanded polystyrene (EPS,Thermocol) used for packaging, decoration, and disposable plates. Thermocol decoration items, plates, cups, and glasses are banned single-use plastics in India since 1 July 2022.', true),
  (8, 'plastic scrap', 'plastic', ARRAY['Sort by resin type,plastic code where possible before disposal', 'Clean off food or chemical residue', 'Keep dry until handed to a scrap dealer', 'Take to a municipal dry-waste centre or authorised recycler', 'For bulk,industrial scrap, contact a CPCB,State PCB-registered plastic recycler directly']::text[], ARRAY['Sold by weight to kabadiwalas,scrap aggregators', 'Processed by registered plastic reprocessors authorised by the State Pollution Control Board', 'Digital scrap marketplaces (e.g., Recykal) connect bulk generators to recyclers']::text[], ARRAY['Segregate by plastic type,colour if feasible', 'Keep dry and free of contamination', 'Sell to authorised recyclers only']::text[], ARRAY['Don''t sell to unregistered,informal recyclers processing waste without safety measures', 'Don''t burn mixed plastic scrap', 'Don''t mix with e-waste, batteries, or other hazardous items']::text[], 'Glass bottles used for beverages, food, or cosmetics. Glass is 100% and infinitely recyclable without any loss of quality.Glass bottles used for beverages, food, or cosmetics. Glass is 100% and infinitely recyclable without any loss of quality.', false),
  (9, 'glass bottle', 'glass', ARRAY['Empty and rinse the bottle', 'Remove metal,plastic caps and lids and dispose of them separately', 'Keep the bottle intact — don''t break it — for safer, higher-value recycling', 'Segregate by colour if your local collector asks for it', 'Hand over to a kabadiwala, glass dealer, or municipal dry-waste centre']::text[], ARRAY['Some beverage brands run bottle deposit,return and reuse systems', 'Collected and sorted into cullet by recyclers — e.g., Karo Sambhav''s ''Dear Cullet'' initiative with Saint-Gobain, which has onboarded over a thousand glass dealers', 'Cullet is melted with sand, soda ash, and limestone to make new glass products']::text[], ARRAY['Rinse before storing for collection', 'Keep bottles whole,unbroken', 'Separate caps, lids, and labels where possible']::text[], ARRAY['Don''t smash bottles before handing them over — it lowers recycling value and creates safety hazards', 'Don''t mix glass with regular wet,dry municipal bins', 'Don''t dispose of glass in general skips where it can injure sanitation workers']::text[], 'Shattered or cracked glass from bottles, jars, windows, or utensils. Needs careful handling due to the injury risk it poses to waste handlers.', true),
  (10, 'broken glass', 'glass', ARRAY['Never place loose broken glass directly into regular waste bags', 'Wrap pieces securely in newspaper, cloth, or thick packaging', 'Place the wrapped glass in a rigid, puncture-proof container (e.g., a cardboard box)', 'Clearly label the container,bag as ''Broken Glass'' or ''Sharp Waste''', 'Hand over to municipal waste collectors or a specialised glass recycler rather than loose bins']::text[], ARRAY['Collected separately for safety, then sent to cullet-processing recyclers', 'Down-cycled into construction materials, glass wool, or tiles if the colour-mix is impure', 'Some MRF operators and zero-waste organisations accept segregated, wrapped broken glass']::text[], ARRAY['Wrap and label clearly before disposal', 'Use gloves when handling', 'Store in a sturdy container away from foot traffic']::text[], ARRAY['Don''t throw loose shards into open dustbins or communal waste', 'Don''t mix with regular recyclables — it endangers waste workers', 'Don''t sweep glass into general dry waste without wrapping it first']::text[], 'Shattered or cracked glass from bottles, jars, windows, or utensils. Needs careful handling due to the injury risk it poses to waste handlers.', true),
  (11, 'glass container', 'glass', ARRAY['Empty and rinse thoroughly, removing any food or product residue', 'Remove metal, plastic, or cork lids and dispose of them separately', 'Keep the container whole and unbroken for safer handling and better recycling value', 'Segregate by colour if your local collector asks for it', 'Hand over to a kabadiwala, glass dealer, or municipal dry-waste centre']::text[], ARRAY['Collected and sorted into cullet through the same recycler network as glass bottles', 'Can be reused directly for home storage before it''s recycled', 'Processed into new glass containers or down-cycled into construction material']::text[], ARRAY['Rinse and dry before storage', 'Keep whole; remove lids separately']::text[], ARRAY['Rinse and dry before storage', 'Keep whole; remove lids separately']::text[], 'Glass jars,containers used for food, cosmetics, or storage. Like bottles, glass containers are infinitely recyclable without loss of quality.', true),
  (12, 'beverage can', 'metal', ARRAY['Empty and rinse out any leftover liquid', 'Crush the can to save storage space (optional)', 'Keep it dry to prevent rust,corrosion, which lowers scrap value', 'Store separately from steel,tin cans if your dealer pays different rates for each', 'Sell to a local kabadiwala,scrap dealer or drop at a dry-waste centre']::text[], ARRAY['Sold by weight to kabadiwalas,scrap dealers — aluminium fetches one of the higher scrap rates', 'Processed by aluminium recyclers into ingots reused for new cans and products', 'Digital scrap platforms like MetalMandi (Attero Recycling) and Kabadiwala Online offer doorstep pickup']::text[], ARRAY['Rinse before storing', 'Crush to save space if storing several', 'Keep separate from steel,tin cans for better pricing']::text[], ARRAY['Don''t leave liquid inside — causes corrosion and attracts pests', 'Don''t burn cans', 'Don''t mix with hazardous waste or e-waste']::text[], 'Aluminium beverage cans (soft drinks, beer). A high-value, infinitely recyclable metal that''s actively bought by scrap dealers across India.', true),
  (13, 'spray can', 'metal', ARRAY['Use up the contents fully before disposal — don''t puncture or crush a can that still has product,pressure in it', 'Never puncture, burn, or crush a pressurised can yourself', 'If it held hazardous contents (paint, pesticide, solvent) and can''t be fully emptied, hand it over as household hazardous waste rather than regular scrap', 'Once genuinely empty, the metal body can go to a scrap dealer,kabadiwala', 'Leave the plastic nozzle,cap attached — recyclers separate it during processing']::text[], ARRAY['Empty cans are accepted by metal scrap dealers,kabadiwalas as aluminium,steel scrap', 'Cans with hazardous residue should go through hazardous-waste handlers authorised under India''s Hazardous and Other Wastes Rules', 'Some municipal hazardous-waste collection drives accept household aerosol cans']::text[], ARRAY['Confirm the can is fully empty before recycling', 'Store upright in a cool place away from heat until disposal', 'Ask your scrap dealer if they accept aerosol cans as metal scrap']::text[], ARRAY['Don''t puncture, crush, or throw a non-empty can into fire or regular trash', 'Don''t store near heat,flames — risk of explosion', 'Don''t dispose of paint,pesticide cans as ordinary waste if any residue remains']::text[], 'Pressurised aerosol,spray cans (deodorant, insecticide, paint), usually aluminium or steel. Can be hazardous and even explosive if not fully emptied before disposal.', true),
  (14, 'metal container', 'metal', ARRAY['Empty out contents completely and rinse if it held food', 'Remove non-metal parts (plastic lids, rubber seals) where possible', 'Flatten or dent large tins to save space, if it''s safe to do so', 'Sell to a local scrap dealer,kabadiwala or drop at a dry-waste centre']::text[], ARRAY['Purchased by kabadiwalas by weight and metal type (steel, tin, aluminium)', 'Processed by metal recyclers,smelters into new sheet metal or ingots', 'Digital scrap platforms offer doorstep pickup for bulk quantities']::text[], ARRAY['Clean and dry before handing over', 'Separate different metal types where you can']::text[], ARRAY['Don''t mix with e-waste or batteries', 'Don''t dispose of rusted, sharp-edged tins loosely — wrap or bundle safely', 'Don''t burn to remove labels or residue']::text[], 'General metal containers such as tins, tiffin boxes, or storage boxes — usually steel, tin-plated steel, or aluminium.', true),
  (15, 'scrap metal', 'metal', ARRAY['Segregate by metal type where possible — ferrous and non-ferrous metals fetch different rates', 'Keep dry and reasonably free of contamination (oil, mixed plastics)', 'Get a rough weight,quantity estimate before contacting a dealer', 'Sell to an authorised scrap metal dealer or use a doorstep-pickup platform']::text[], ARRAY['Purchased by weight through kabadiwalas, scrap yards, and digital platforms (MetalMandi, ScrapUncle, Kabadiwala Online)', 'Formal recyclers melt and reprocess metal into new sheets, rods, or ingots', 'For bulk,industrial scrap, use CPCB,State Pollution Control Board-registered recyclers with proper transport documentation']::text[], ARRAY['Segregate by metal type for the best price', 'Get material weighed transparently (digital weighing where available)', 'Keep documentation for bulk transactions']::text[], ARRAY['Don''t sell hazardous,contaminated industrial scrap to unregistered dealers', 'Don''t leave in the open where it rusts and loses value', 'Don''t mix with e-waste or batteries']::text[], 'Mixed metal waste or off-cuts — iron, steel, copper, brass, or aluminium — typically from households, construction, or repair work.', true),
  (16, 'aluminium foil', 'metal', ARRAY['Clean off food residue and grease as much as possible', 'Scrunch several pieces into a ball to make handling easier', 'Keep dry and separate from wet waste', 'Sell to a scrap dealer,kabadiwala along with other aluminium scrap', 'If heavily soiled and can''t be cleaned, dispose of as general waste rather than contaminating a clean batch']::text[], ARRAY['Purchased by kabadiwalas,scrap dealers as aluminium scrap by weight', 'Melted down by aluminium recyclers into ingots reused in packaging, utensils, and other products']::text[], ARRAY['Rinse,wipe off food residue when possible', 'Bundle clean foil into a ball before handing over']::text[], ARRAY['Don''t recycle heavily food-contaminated foil together with clean batches', 'Don''t burn aluminium foil', 'Don''t mix with plastic-lined foil packets (e.g., chip packet linings) — those count as multilayer plastic, not pure metal']::text[], 'Thin aluminium sheeting used for food wrapping and packaging. Recyclable, but food residue and grease lower its recycling value.', true),
  (17, 'foil food container', 'metal', ARRAY['Scrape off and rinse away food residue thoroughly', 'Let it air-dry before storing for recycling', 'Flatten or stack multiple trays together', 'Hand over to a scrap dealer,kabadiwala as aluminium scrap']::text[], ARRAY['Collected by kabadiwalas,scrap dealers along with other aluminium items', 'Reprocessed by aluminium recyclers into ingots for new products']::text[], ARRAY['Clean thoroughly before storing,selling', 'Stack trays to save space']::text[], ARRAY['Don''t dispose of with food residue still stuck to it — attracts pests and lowers scrap value', 'Don''t burn foil containers', 'Don''t mix heavily soiled trays with clean recyclables']::text[], 'Disposable aluminium foil trays,containers commonly used for takeaway food and baking. Recyclable as aluminium scrap once cleaned.', true),
  (18, 'steel can', 'metal', ARRAY['Empty out contents completely and rinse the can', 'Peel off the paper label if it comes away easily (most recyclers can process it either way)', 'Flatten if you have a can-crusher, or leave it whole', 'Fold or cover sharp edges from the lid for safety', 'Sell to a kabadiwala,scrap dealer as steel,tin scrap']::text[], ARRAY['Purchased by kabadiwalas,scrap dealers by weight as steel scrap', 'Steel recyclers melt cans down for reuse in construction and manufacturing', 'Digital scrap platforms offer doorstep pickup for bulk quantities']::text[], ARRAY['Rinse before storing', 'Handle carefully due to sharp cut edges', 'Sell along with other ferrous scrap']::text[], ARRAY['Don''t leave food residue inside — attracts pests and causes rusting', 'Don''t discard loose sharp lids in regular trash — wrap them first', 'Don''t burn cans']::text[], 'Steel (often tin-plated) cans used for canned food like vegetables, fish, or beans. Magnetic, and easy to separate from other metals for recycling.', true),
  (19, 'cooking pot', 'metal', ARRAY['If still usable, consider donating rather than discarding', 'If damaged beyond use, clean off any food or grease residue', 'Separate by metal type if you have several items (steel, aluminium, brass, copper-bottomed)', 'Sell as metal scrap to a kabadiwala,scrap dealer, or use a neighbourhood utensil-exchange (''bartan wala'') service common in Indian cities']::text[], ARRAY['Kabadiwalas and scrap dealers buy old cookware by weight and metal type', 'Metal recyclers melt and reprocess it into new utensils, sheets, or ingots', 'Local old-for-new utensil exchange vendors that visit neighbourhoods']::text[], ARRAY['Donate usable cookware instead of scrapping it', 'Clean before handing over', 'Separate by metal type for better value']::text[], ARRAY['Don''t discard usable cookware — donate or exchange it instead', 'Don''t mix different metal types when selling if avoidable', 'Don''t throw into general household waste — always route through scrap channels']::text[], 'Metal cookware such as old pots, pans, and utensils — usually steel, aluminium, or brass. Generally higher-value scrap than cans or foil.', true),
  (20, 'cardboard box', 'cardboard and paper', ARRAY['Remove tape, plastic wrap, bubble wrap, or thermocol packing material', 'Flatten the box to save space', 'Keep it dry — wet or soiled cardboard is harder to recycle', 'Bundle it with other paper,cardboard waste', 'Sell to a kabadiwala,raddiwala or hand over to a municipal dry-waste centre']::text[], ARRAY['Purchased by kabadiwalas,raddiwalas (paper scrap dealers) by weight', 'Processed by paper mills into recycled kraft paper and new cardboard', 'Corporate programmes like ITC''s WOW (Wellbeing Out of Waste) collect and channel paper,cardboard waste through registered recyclers']::text[], ARRAY['Flatten before storing,selling', 'Remove non-paper attachments (tape, plastic, styrofoam)', 'Keep dry']::text[], ARRAY['Don''t recycle heavily food-soiled or greasy cardboard (e.g., pizza boxes) with clean paper', 'Don''t leave it wet — mould and moisture ruin recyclability', 'Don''t burn cardboard']::text[], 'Corrugated cardboard boxes used for packaging and shipping — one of the most commonly and easily recycled materials in India.', true),
  (21, 'cardboard packaging', 'cardboard and paper', ARRAY['Flatten and remove plastic tape, labels, or foam inserts', 'Keep dry and separate from wet waste', 'Bundle with other cardboard for collection', 'Hand over to a raddiwala (paper scrap dealer) or municipal dry-waste centre']::text[], ARRAY['Sold by weight to kabadiwalas,raddiwalas', 'Reprocessed by paper mills into recycled paperboard', 'Producer,retailer take-back or EPR-linked packaging collection schemes']::text[], ARRAY['Flatten and bundle for storage', 'Remove non-paper components before recycling• Flatten and bundle for storage', 'Remove non-paper components before recycling']::text[], ARRAY['Don''t mix with wax-coated or heavily laminated cartons — often not recyclable in the standard paper stream', 'Don''t leave it outdoors where it can get wet', 'Don''t burn it']::text[], 'General cardboard,paperboard packaging — cartons, sleeves, product boxes — used for retail and shipping.', true),
  (22, 'paper', 'cardboard and paper', ARRAY['Keep dry and free from food or liquid contamination', 'Remove plastic sleeves, spiral bindings, or metal clips,staples where possible', 'Bundle or stack paper together', 'Sell to a raddiwala,kabadiwala or drop at a municipal dry-waste centre']::text[], ARRAY['Purchased by weight by local raddiwalas (paper scrap dealers)', 'Reprocessed by paper mills into recycled paper products', 'School,corporate paper-recycling drives (e.g., ITC WOW) collect and channel paper waste']::text[], ARRAY['Keep dry and clean', 'Remove staples,clips,plastic where feasible', 'Store paper flat or bundled']::text[], ARRAY['Don''t mix with wet or food-soiled paper', 'Don''t burn paper waste', 'Don''t discard confidential documents without shredding,appropriate disposal']::text[], 'General mixed paper waste, including office paper, printouts, and other miscellaneous paper items.', true),
  (23, 'white paper', 'cardboard and paper', ARRAY['Keep separate from coloured or glossy paper for better recycling value', 'Remove staples, clips, and plastic covers', 'Keep dry and flatten where possible', 'Sell to a raddiwala or hand it to a dry-waste collection centre']::text[], ARRAY['Fetches a better price from paper scrap dealers due to higher fibre quality', 'Processed by paper mills into recycled writing,printing paper', 'Institutional recycling programmes (offices, schools) can collect this in bulk']::text[], ARRAY['Segregate from coloured,glossy,laminated paper', 'Store dry and bundled']::text[], ARRAY['Don''t mix with wet or food-contaminated paper', 'Don''t shred and mix with other waste without a plan to recycle the shreds', 'Don''t burn paper']::text[], 'Plain white paper (office,printer paper, notebook sheets) — higher-quality recyclable fibre than mixed or coloured paper.', true),
  (24, 'brown paper', 'cardboard and paper', ARRAY['Keep dry and free from tape, plastic, or food residue', 'Flatten and bundle for storage', 'Sell to a raddiwala,kabadiwala or drop at a dry-waste centre']::text[], ARRAY['Purchased by weight by paper scrap dealers', 'Reprocessed by paper mills into recycled kraft paper and cardboard']::text[], ARRAY['Keep clean, dry, and flat', 'Bundle with other paper,cardboard waste']::text[], ARRAY['Don''t mix oil-stained brown paper (e.g., food wrapping) with clean recyclables', 'Don''t burn it', 'Don''t leave it outdoors exposed to rain']::text[], 'Kraft,brown paper used for packaging, envelopes, and wrapping — sturdy and highly recyclable.', true),
  (25, 'newspaper', 'cardboard and paper', ARRAY['Keep dry and stack neatly', 'Remove plastic wrapping or inserts if present', 'Bundle and tie with string for easy handling', 'Sell directly to a raddiwala,kabadiwala or drop at a municipal dry-waste centre']::text[], ARRAY['One of the highest-demand items for local raddiwalas, sold by weight', 'Reprocessed by paper mills into newsprint and other recycled paper products']::text[], ARRAY['Stack and bundle neatly', 'Keep dry', 'Sell regularly rather than letting it pile up and dampen']::text[], ARRAY['Don''t let newspapers get wet or mouldy', 'Don''t burn old newspapers', 'Don''t mix with wet waste or food wrappers']::text[], 'Old newspapers — one of the most commonly collected and recycled paper products in Indian households, usually bought directly by the local raddiwala.', true),
  (26, 'paper cup', 'cardboard and paper', ARRAY['Empty out any liquid completely', 'Don''t assume it can go with regular clean paper,cardboard recycling', 'Check if your city has a specialised paper-cup recycling collection point (rare, but growing)', 'If no such facility exists, dispose of via general dry waste rather than mixing with wet waste', 'Prefer reusable cups,mugs where possible to reduce this hard-to-recycle waste']::text[], ARRAY['A few specialised recyclers can separate the plastic lining from the paperboard, but this infrastructure is limited in India', 'Most standard raddiwalas,paper mills reject paper cups as contaminants', 'Corporate sustainability programmes occasionally run dedicated paper-cup collection drives']::text[], ARRAY['Rinse out liquid before discarding', 'Look for a dedicated collection point if available', 'Choose reusable cups when you have the option']::text[], ARRAY['Don''t put it in the same pile as clean white paper,newspaper for recycling', 'Don''t assume ''paper'' labelling means it''s fully recyclable', 'Don''t burn it (releases fumes from the plastic lining)']::text[], 'Disposable cups made of paperboard with a thin plastic (usually polyethylene) lining to make them leak-proof. That plastic coating makes them difficult to recycle through standard paper streams.', false),
  (27, 'tetra pak', 'cardboard and paper', ARRAY['Segregate aseptic carton packaging as dry recyclable waste at home.', 'Deposit directly at designated Tetra Pak consumer drop-off centers or local dry waste collection points.']::text[], ARRAY['Processed by authorized recyclers to separate paper pulp from aluminum and polymer layers.', 'Recycled into corrugated boxes, paper products, roof sheets, and upcycled furniture.']::text[], ARRAY['Flatten and rinse cartons thoroughly before dropping off.', 'Store in the blue dry waste bin separate from organic waste.']::text[], ARRAY['Do not throw tetra paks into wet waste bins or compost pits.', 'Do not litter cartons in drains, streets, or public areas.']::text[], 'Multi-layered paperboard carton packaging containing thin protective polymer and aluminum layers used for liquids like juice and milk.', true),
  (28, 'book', 'cardboard and paper', ARRAY['Donate usable books to community libraries, schools, or NGO collection drives such as Goonj.', 'Place worn or damaged books into the blue dry waste bin for paper recycling.']::text[], ARRAY['Repackaged and redistributed to underserved rural students through educational campaigns.', 'Pulped at paper recycling mills to produce fresh recycled paper products.']::text[], ARRAY['Keep books dry, clean, and bundled before handing over to recyclers or donation centers.', 'Organize institutional book collection drives for surplus literature.']::text[], ARRAY['Do not mix paper books with wet organic kitchen waste.', 'Do not burn books or paper waste outdoors.']::text[], 'Bound paper reading materials, textbooks, notebooks, and novels.', true),
  (29, 'syringe', 'medical', ARRAY['Syringes without needles or with detached needles go into Red biohazard plastic bags or containers.', 'Syringes with fixed needles or loose needles must be placed into puncture-proof, tamper-proof White sharps containers.']::text[], ARRAY['Plastic barrels in Red bags are autoclaved, microwaved, and shredded for registered plastic recycling.', 'Metal needles in White containers undergo autoclaving,dry heat sterilization and shredding for metal recovery.']::text[], ARRAY['Use needle cutters or destroyers at the point of use to isolate metal needles safely.', 'Hand over domestic medical sharps as special care , domestic hazardous waste.']::text[], ARRAY['Do not throw syringes loosely into municipal dry bins or general household trash.', 'Do not reuse disposable medical syringes.']::text[], 'Medical fluid injection devices comprising plastic barrels, plungers, and optional fixed or detachable stainless steel needles.', true),
  (30, 'mask', 'medical', ARRAY['Clinical or bio-contaminated masks go into Yellow non-chlorinated biohazard bags for incineration.', 'Household face masks should be wrapped securely in paper or pouches and disposed of as sanitary , special care waste.']::text[], ARRAY['Non-recyclable due to infectious biohazard contamination; disposed of via high-temperature incineration or plasma pyrolysis.']::text[], ARRAY['Wrap used masks securely in wrapping paper before placing in non-biodegradable waste bins.', 'Separate from recyclable paper and plastic streams.']::text[], ARRAY['Do not throw open or unsealed masks onto streets or open public grounds.', 'Do not place contaminated masks into green wet waste or blue recycling bins.']::text[], 'Protective personal mask equipment worn over mouth and nose to prevent microbial infection transmission.', false),
  (31, 'glove', 'medical', ARRAY['Contaminated rubber or latex medical gloves must be segregated into Red biohazard bags,containers in healthcare facilities.', 'Household medical gloves must be wrapped securely and handed over as domestic special care waste.']::text[], ARRAY['Autoclaved or microwaved,hydroclaved followed by shredding and processing by authorized rubber,plastic recyclers.']::text[], ARRAY['Segregate gloves immediately after single-use into non-chlorinated red containers.', 'Ensure proper personal protective equipment when handling medical waste.']::text[], ARRAY['Do not mix used gloves with compostable wet organic waste.', 'Do not discard unsterilized medical gloves into general municipal garbage.']::text[], 'Disposable protective gloves made of latex, nitrile, or rubber used in medical examinations and surgical care.', true),
  (32, 'medicine pack', 'medical', ARRAY['Empty cardboard outer cartons go to blue dry waste paper recycling.', 'Empty plastic,foil blister strips go to dry plastic waste; packs containing residual expired,cytotoxic drugs go to Yellow biohazard bins or pharmacy return channels.']::text[], ARRAY['Clean cardboard and plastic packaging recycled through municipal dry waste channels.', 'Contaminated drug packaging incinerated at Common Bio-medical Waste Treatment Facilities.']::text[], ARRAY['Scratch out or remove personal prescription information from medicine labels prior to disposal.', 'Separate paper boxes from foil and plastic blister packs.']::text[], ARRAY['Do not throw unused or expired medicines inside packs into household sink drains or open soil.', 'Do not mix cytotoxic drug packaging with general dry waste.']::text[], 'Packaging items for pharmaceutical products including foil blister packs, cardboard cartons, and plastic,glass pill bottles.', true),
  (33, 'gauze', 'medical', ARRAY['Blood-soaked or contaminated medical gauze must be placed in Yellow non-chlorinated biohazard bags.', 'Household special care gauze dressings must be securely wrapped in paper,pouches before handing over.']::text[], ARRAY['Non-recyclable due to infectious biological fluids; disposed of via incineration or plasma pyrolysis.']::text[], ARRAY['Securely wrap soiled dressings in suitable pouches or paper.', 'Hand over to authorized special care , biomedical waste collectors.']::text[], ARRAY['Do not place contaminated gauze into compost bins or green wet waste bins.', 'Do not discard unwrapped soiled cotton gauze into public waste receptacles.']::text[], 'Absorbent cotton cloth mesh used for dressing wounds, surgical procedures, and medical blood absorption.', false),
  (34, 'electronic board chip', 'e-waste devices', ARRAY['Store in dedicated e-waste bins or storage lockers and hand over to certified e-waste recyclers.', 'Deposit at authorized Material Recovery Facilities (MRFs) or collection points.']::text[], ARRAY['Processed in specialized e-waste facilities to safely extract precious metals (gold, copper, silver) and treat heavy metals.']::text[], ARRAY['Segregate circuit boards from general municipal solid waste.', 'Verify that the recycler possesses environmental certification.']::text[], ARRAY['Do not burn electronic chips in open fires or submit to informal acid-bath recyclers.', 'Do not throw into landfills or regular garbage bins.']::text[], 'Printed circuit boards (PCBs) and semiconductor microchips containing electronic circuitry and metal components.', true),
  (35, 'cable', 'e-waste devices', ARRAY['Collect electrical wires and data cables separately and deposit at authorized e-waste pickup centers.', 'Schedule door-to-door bulk e-waste collection.']::text[], ARRAY['Mechanical granulating and stripping to isolate copper and aluminum wiring from outer plastic insulation.']::text[], ARRAY['Coil and tie cables neatly when storing for e-waste pickup.', 'Keep dry and free from chemical contamination.']::text[], ARRAY['Do not burn cable insulation outdoors to recover copper.', 'Do not dump with household organic waste.']::text[], 'Insulated wiring and power cords used for electrical conductivity and electronic data transfer.', true),
  (36, 'small appliance', 'e-waste devices', ARRAY['Store in e-waste storage cages,lockers and dispose of through authorized e-waste recyclers.', 'Arrange door-to-door e-waste pickup or drop off at municipal e-waste collection centers.']::text[], ARRAY['Disassembled into metallic housings, internal copper motors, circuit boards, and plastic polymers for material recovery.']::text[], ARRAY['Unplug and clean appliances before handing over for recycling.', 'Remove any loose batteries prior to appliance disposal.']::text[], ARRAY['Do not throw appliances into municipal refuse bins or open dumpsites.', 'Do not dismantle electrical appliances without protective equipment.']::text[], 'Small household electronic and electrical devices such as kettles, irons, toasters, and hair dryers.', true),
  (37, 'laptop computer', 'e-waste devices', ARRAY['Donate functional laptops to schools or NGOs, or hand over non-functional units to certified e-waste companies.', 'Utilize corporate asset management reverse logistics services.']::text[], ARRAY['Functional units refurbished for circular reuse; non-functional units disassembled for metal, glass, lithium, and circuit board recovery.']::text[], ARRAY['Permanently erase or destroy all sensitive digital storage data before disposal.', 'Store in dedicated e-waste collection bins.']::text[], ARRAY['Do not throw laptops into general municipal trash or landfills.', 'Do not give laptops to uncertified informal scrap vendors.']::text[], 'Portable personal computer equipped with a screen, keyboard, circuit board, and rechargeable battery.', true),
  (38, 'mobile tablet', 'e-waste devices', ARRAY['Deposit at certified mobile e-waste drop-off bins or arrange door-to-door e-waste collection.', 'Donate working devices to community education initiatives.']::text[], ARRAY['Refurbished for secondary usage or recycled to recover precious metals, rare earth elements, glass, and polymers.']::text[], ARRAY['Perform factory data resets, remove SIM,SD cards, and ensure secure data deletion.', 'Keep intact without crushing battery components.']::text[], ARRAY['Do not dispose of smartphones in domestic waste dustbins.', 'Do not incinerate mobile phones or puncture lithium batteries.']::text[], 'Compact touchscreen mobile phones, smartphones, and tablet computers.', true),
  (39, 'battery cell', 'e-waste devices', ARRAY['Segregate as domestic hazardous , special care waste at source.', 'Deposit in specialized battery drop-off bins or hand over to authorized e-waste recyclers.']::text[], ARRAY['Chemical extraction and hydrometallurgical processing to recover heavy metals, lead, nickel, lithium, and zinc.']::text[], ARRAY['Store in dry, non-conductive containers away from water and flame.', 'Tape terminals of rechargeable lithium cells to prevent short circuits.']::text[], ARRAY['Do not throw batteries into regular household trash bins or landfills.', 'Do not throw batteries into fires or subject them to high thermal exposure.']::text[], 'Dry cell batteries, button cells, and lithium-ion batteries used to power electronic gadgets.', true),
  (40, 'clothing', 'fabric', ARRAY['Donate clean, wearable clothing to NGO collection drives like Goonj (''Cloth for Work'' , ''Ek Jodi Kapada'').', 'Unwearable, torn textiles should be handed over to authorized dry waste recyclers.']::text[], ARRAY['Upcycled into products like purses, file folders, mats, and cloth pads (''Green by Goonj'').', 'Shredded into industrial fiber or recycled yarn for textile manufacturing.']::text[], ARRAY['Wash, dry, iron, and neatly fold clothes before dropping off at donation camps.', 'Separate cotton fabrics for specialized upcycling drives.']::text[], ARRAY['Do not throw wearable garments into municipal garbage bins or wet waste.', 'Do not dump dirty or damp clothes in collection drives.']::text[], 'Garments and apparel made of stitched, woven, or knitted fabrics like shirts, trousers, sarees, and coats.', true),
  (41, 'rag', 'fabric', ARRAY['Clean textile scraps and katran should be handed over to upcycling initiatives or dry waste collectors.', 'Contaminated rags should be segregated as dry non-recyclable waste.']::text[], ARRAY['Upcycled into stuffing, patchwork products, and utility items.', 'Processed by fiber shredders for industrial rag recycling.']::text[], ARRAY['Keep textile scraps dry and segregated from wet garbage.', 'Collect clean tailor waste (katran) for upcycling stalls.']::text[], ARRAY['Do not burn textile rags contaminated with oils or solvents.', 'Do not mix rags into organic composting pits.']::text[], 'Scraps of worn-out cloth, rags, and leftover textile pieces.', true),
  (42, 'shoes', 'fabric', ARRAY['Donate paired, wearable shoes and sports footwear to community donation drives.', 'Non-usable footwear should be handed over to dry waste collectors.']::text[], ARRAY['Wearable footwear cleaned and redistributed to rural communities.', 'Damaged shoes dismantled to recover rubber soles and synthetic uppers.']::text[], ARRAY['Tie shoe pairs together securely before dropping at collection centers.', 'Clean dirt off shoes before donation.']::text[], ARRAY['Do not throw single or broken shoes into public drains or rivers.', 'Do not mix footwear with wet organic waste.']::text[], 'Footwear constructed from fabric, leather, synthetic materials, and rubber soles.', true),
  (43, 'bed', 'furniture', ARRAY['Donate usable bed frames to institutions or NGOs.', 'Arrange scheduled bulk dry waste collection with municipal local bodies or authorized agencies.']::text[], ARRAY['Wooden beds disassembled for timber upcycling or wood chip processing.', 'Metal frames sent to scrap foundries for metal melting and recycling.']::text[], ARRAY['Dismantle large bed structures safely before transport.', 'Keep wooden structures dry to prevent fungal decay prior to recycling.']::text[], ARRAY['Do not dump old beds on footpaths, roadsides, or vacant land.', 'Do not burn wooden or upholstered beds.']::text[], 'Large furniture structures for sleeping made from timber, plywood, or metal tubing.', true),
  (44, 'chair', 'furniture', ARRAY['Donate usable home,office chairs to NGOs or educational centers.', 'Hand over broken chairs to municipal dry waste scrap collectors.']::text[], ARRAY['Plastic chairs granules-recycled; metal and wooden chairs disassembled for scrap recycling.']::text[], ARRAY['Repair minor damages if possible to extend furniture lifecycle.', 'Stack chairs safely for bulk waste collection.']::text[], ARRAY['Do not abandon broken chairs in public streets or parks.', 'Do not burn molded plastic chairs.']::text[], 'Seating furniture constructed from wood, molded plastic, steel, or fabric upholstery.', true),
  (45, 'dresser', 'furniture', ARRAY['Donate usable dressing tables to charity organizations.', 'Schedule bulk dry waste pickup through municipal authorized agencies.']::text[], ARRAY['Wooden cabinet frames shredded into particle board material; glass mirrors recycled separately.']::text[], ARRAY['Remove glass mirrors carefully and wrap securely to protect handlers.', 'Empty all drawers before disposal.']::text[], ARRAY['Do not smash glass mirrors inside general garbage containers.', 'Do not dump wooden dressers on public roadsides.']::text[], 'Wooden or engineered board cabinet unit with drawers and mirrors used for clothing storage and dressing.', true),
  (46, 'table', 'furniture', ARRAY['Donate study, dining, or office tables to institutions or NGOs.', 'Hand over damaged tables to authorized municipal scrap collectors.']::text[], ARRAY['Wooden tops processed into recycled wood products or biomass fuel pellets.', 'Metal legs and hardware melted in scrap metal plants.']::text[], ARRAY['Keep dry and store in covered areas prior to collection.', 'Unscrew detachable legs for easy transport.']::text[], ARRAY['Do not discard tables into water bodies, storm drains, or open roads.', 'Do not burn engineered wood tables containing adhesives.']::text[], 'Flat-topped elevated furniture supported by legs, made of timber, metal, or composite board.', true),
  (47, 'sofa', 'furniture', ARRAY['Donate functional couches to social organizations.', 'Arrange specialized bulk waste collection services with municipal agencies.']::text[], ARRAY['Stripped to recover wooden framing, steel springs, and textile upholstery for separate recycling.']::text[], ARRAY['Keep covered during transit to keep dry and prevent mold.', 'Disassemble modular cushions prior to collection.']::text[], ARRAY['Do not burn foam padding or synthetic leather upholstery outdoors.', 'Do not dump sofas in vacant plots or water channels.']::text[], 'Upholstered seating furniture built with timber,metal frames, spring cushions, foam, and fabric,leather covering.', true),
  (48, 'cabinet', 'furniture', ARRAY['Donate usable storage cabinets to schools, colleges, or Goonj.', 'Hand over old steel or wooden cabinets to authorized scrap recyclers.']::text[], ARRAY['Steel almirahs and cabinets melted for 100% metal recycling.', 'Wooden cabinets processed for composite board manufacturing.']::text[], ARRAY['Lock or secure doors during transport to prevent damage or injury.', 'Remove all personal files and stored items prior to disposal.']::text[], ARRAY['Do not abandon heavy storage cabinets in public pathways.', 'Do not mix furniture items with daily municipal kitchen garbage.']::text[], 'Enclosed storage furniture with doors, shelves, or drawers made of steel or timber.', true),
  (49, 'cooked food scraps', 'organic', ARRAY['Segregate into the Green wet waste bin at source.', 'Process on-site using aerobic compost pits, in-vessel organic waste composters (OWC), or bio-methanation plants.']::text[], ARRAY['Converted into nutrient-rich organic compost,manure for gardens.', 'Processed in bio-methanation reactors to produce methane-rich biogas for cooking or energy.']::text[], ARRAY['Segregate strictly from plastic wrappers, disposable plates, and foil.', 'Mix with dry bulking materials (sawdust, cocopeat, dry leaves) during composting.']::text[], ARRAY['Do not dispose of cooked food scraps inside plastic carry bags.', 'Do not throw food waste into open drains, water bodies, or streets.']::text[], 'Leftover prepared meals, cooked rice, curries, and catering food waste.', true),
  (50, 'fruit vegetable scraps', 'organic', ARRAY['Collect in Green wet waste bins for decentralized home or community composting.', 'Process via vermicomposting beds or aerobic compost boxes.']::text[], ARRAY['Converted into high-quality organic manure and vermicompost for agricultural and garden soil.']::text[], ARRAY['Maintain proper moisture balance in compost units by adding dry leaves or straw.', 'Chop large fruit peels to accelerate decomposition.']::text[], ARRAY['Do not mix fruit and vegetable peels with plastic packaging, glass, or metals.', 'Do not dump wet peels on public roads or storm drains.']::text[], 'Uncooked kitchen bio-waste including vegetable peels, fruit skins, stalks, and fruit seeds.', true),
  (51, 'garden waste', 'organic', ARRAY['Mulch and compost fallen leaves and grass trimmings on-site in leaf composters, pits, or cages.', 'Hand over large tree branches or excess horticulture waste to municipal horticulture collection vehicles.']::text[], ARRAY['Transformed into leaf mold compost, soil mulch, or compressed biomass pellets.']::text[], ARRAY['Store garden trimmings separately on your premises.', 'Shred branches into small wood chips to speed up composting.']::text[], ARRAY['Do not burn dry leaves, grass, or tree trimmings.', 'Do not mix garden waste with non-biodegradable dry waste or hazardous items.']::text[], 'Plant-based bio-waste from horticulture including leaves, grass clippings, weeds, pruned twigs, and small branches.', true),
  (52, 'slippers', 'rubber', ARRAY['Donate usable rubber slippers , chappals to Goonj or community drives.', 'Non-usable rubber slippers must be placed in the blue dry waste bin.']::text[], ARRAY['Usable pairs redistributed to rural school children and communities.', 'Worn rubber soles ground down into crumb rubber for rubberized flooring and industrial products.']::text[], ARRAY['Tie pairs together before dropping off for donation.', 'Keep dry and clean before recycling disposal.']::text[], ARRAY['Do not burn rubber footwear outdoors.', 'Do not throw slippers into open drains or river bodies.']::text[], 'Casual footwear made of natural rubber, EVA polymer foam, or synthetic rubber.', true),
  (53, 'general stationary', 'stationary', ARRAY['Donate usable items (rulers, erasers, sharpeners) through institutional collection camps or school kits.', 'Discard broken plastic items into blue dry recyclable bins.']::text[], ARRAY['Usable supplies distributed to rural school children (''School to School'' kits).', 'Plastic stationary components shredded and recycled by registered plastic recyclers.']::text[], ARRAY['Segregate plastic stationery from paper and organic waste.', 'Organize stationery drives at schools and corporate offices.']::text[], ARRAY['Do not mix plastic office supplies into wet kitchen waste.', 'Do not litter stationary items in open school yards or streets.']::text[], 'Miscellaneous plastic and composite office,school supplies including plastic scales, erasers, sharpeners, and organizers.', true),
  (54, 'notebooks', 'stationary', ARRAY['Donate fresh or partially used notebooks to educational campaigns.', 'Discard used paper notebooks into blue dry paper recycling bins.']::text[], ARRAY['Blank pages assembled into upcycled notebooks; written paper repulped at paper recycling mills.']::text[], ARRAY['Remove plastic sleeves or spiral binding before sending paper pages for recycling.', 'Save unused blank pages from old registers.']::text[], ARRAY['Do not burn paper notebooks or registers.', 'Do not throw paper notebooks into wet organic waste bins.']::text[], 'Paper exercise books, writing registers, and memo pads used for academic and professional writing.', true),
  (55, 'metal supplies', 'stationary', ARRAY['Donate functional staplers, hole punches, and metal clips.', 'Place broken metal stationery items into blue dry waste bins for metal scrap collection.']::text[], ARRAY['Melted down in scrap metal processing facilities to produce recycled steel and aluminum products.']::text[], ARRAY['Keep metal stationery dry to prevent heavy rusting before recycling.', 'Collect small paper clips in a container before disposal.']::text[], ARRAY['Do not throw loose metal clips into garden soil or compost pits.', 'Do not mix scrap metal with organic kitchen waste.']::text[], 'Metal office stationery items including staplers, paper clips, binder clips, metal hole punches, and steel pins.', true),
  (56, 'pens', 'stationary', ARRAY['Donate working pens to school drives.', 'Discard spent plastic ballpoint pens and markers in the blue dry plastic waste bin.']::text[], ARRAY['Plastic pen bodies shredded and recycled by authorized plastic recycling facilities.']::text[], ARRAY['Use refillable pens to minimize single-use plastic waste generation.', 'Segregate metal nibs,clips if easily detachable.']::text[], ARRAY['Do not throw plastic pens into composting bins or open land.', 'Do not burn plastic pens outdoors.']::text[], 'Plastic or metal writing instruments containing ink refills and nibs.', true),
  (57, 'sharp stationary', 'stationary', ARRAY['Wrap sharp blades or scissors securely in heavy cardboard,paper or put inside a rigid container.', 'Hand over as special care , domestic hazardous waste or dry waste.']::text[], ARRAY['Disassembled metal blades recycled with industrial metal scrap.']::text[], ARRAY['Shield cutting edges or retract utility cutter blades prior to disposal.', 'Label wrapped packages containing sharp stationery to alert waste handlers.']::text[], ARRAY['Do not throw exposed cutter blades or scissors loosely into plastic refuse bags.', 'Do not place sharp blades in green wet waste bins.']::text[], 'Cutting stationery tools such as scissors, paper cutter utility knives, craft scalpels, and geometry compasses.', true),
  (58, 'pencils', 'stationary', ARRAY['Donate usable length pencils to students.', 'Short wooden pencil stubs can go to dry waste or home composting pits.']::text[], ARRAY['Untreated natural wood casing bio-degrades naturally in organic composting systems.']::text[], ARRAY['Collect unsharpened or full-length pencils for rural student kits.', 'Separate plastic ferrule,eraser tips if composting wooden stubs.']::text[], ARRAY['Do not throw usable pencils into municipal trash.', 'Do not litter pencil sharpenings in open public spaces.']::text[], 'Wooden writing pencils containing non-toxic graphite cores and optional rubber eraser tips.', true),
  (59, 'cigarette butt', 'other', ARRAY['Segregate cigarette and bidi butts along with dry non-biodegradable waste at home and workplaces.', 'Channelize towards authorized recycling or end-of-life processing (waste-to-energy , co-processing).']::text[], ARRAY['Chemical treatment and recovery of cellulose acetate from discarded filters to manufacture recycled polymer products.', 'Thermal co-processing in cement kilns or waste-to-energy plants.']::text[], ARRAY['Ensure cigarette butts are fully extinguished before placing in dry waste bins.', 'Follow safe disposal instructions on packaging and deposit in designated ash receptacles.']::text[], ARRAY['Do not litter cigarette butts on roads, footpaths, parks, or soil (cellulose acetate takes over 2 years to achieve just 37.8% degradation).', 'Do not throw burning butts into dry waste bins or organic compost bins.']::text[], 'Toxic smoking waste filter ends composed of 95% cellulose acetate, wrapping paper, rayon, and residual tobacco chemicals.', true)
ON CONFLICT (class_id) DO UPDATE SET
  name = EXCLUDED.name,
  super_category = EXCLUDED.super_category,
  disposal_advice = EXCLUDED.disposal_advice,
  recycling_options = EXCLUDED.recycling_options,
  dos = EXCLUDED.dos,
  donts = EXCLUDED.donts,
  description = EXCLUDED.description,
  is_recyclable = EXCLUDED.is_recyclable;
