// services/blogScraper.js
export async function fetchScrapImpactBlogs() {
  // Directly returning curated environmental hazard data focused entirely on waste harm
  return [
    {
      id: 'hazard-1',
      title: 'Polymer Leaching: How Microplastics Disrupt Hormonal Pathways',
      snippet: 'Discarded plastics breakdown under UV and friction, releasing endocrine-disrupting chemicals (EDCs) like phthalates and BPA directly into soil and runoff water systems.',
      category: 'Plastics',
      urgency: 'TOXIC LEACH',
      accentColor: '#e64a19',
      source: 'EcoToxicology Research Lab',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-2',
      title: 'E-Waste Heavy Metal Seepage: Lead and Cadmium in Groundwater',
      snippet: 'Improperly discarded circuit boards and lithium batteries corrode in landfills, leaking toxic lead, mercury, and cadmium into surrounding aquifers and local ecosystems.',
      category: 'E-Waste',
      urgency: 'HEAVY METALS',
      accentColor: '#c2185b',
      source: 'Global Electronic Waste Monitor',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-3',
      title: 'Organic Food & Textile Waste: Accelerated Methane Generation',
      snippet: 'When natural fibers and organic waste are compressed without oxygen in landfills, they produce massive methane plumes with 80x the warming power of carbon dioxide.',
      category: 'Textiles & Organic Waste',
      urgency: 'METHANE RISK',
      accentColor: '#7b1fa2',
      source: 'Climate Impact Coalition',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-4',
      title: 'Hazardous Chemical Sludge: Acidic Industrial Scrap Exposure',
      snippet: 'Unregulated dumping of chemical waste and industrial solvents burns through soil microbiomes, wiping out vital organisms necessary for regional vegetation growth.',
      category: 'Hazardous Scrap',
      urgency: 'CRITICAL',
      accentColor: '#d32f2f',
      source: 'Industrial Safety Bureau',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-5',
      title: 'Deforestation Impact: The Carbon Toll of Single-Use Cardboard',
      snippet: 'Unrecycled paper and packaging products drive intensive logging cycles, destroying old-growth forests that act as primary planetary carbon sinks.',
      category: 'Paper & Cardboard',
      urgency: 'DEFORESTATION',
      accentColor: '#f57c00',
      source: 'Forestry Defense Registry',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-6',
      title: 'Raw Metal Extraction: Acid Mine Drainage and Habitat Loss',
      snippet: 'Mining raw ores to replace unrecovered scrap metals produces toxic sulfuric acid runoff, devastating aquatic life and poisoning river ecosystems downstream.',
      category: 'Metals',
      urgency: 'EXTRACTION HARM',
      accentColor: '#558b2f',
      source: 'Earth Mineral Watch',
      link: 'https://www.sciencedaily.com',
    },
    {
      id: 'hazard-7',
      title: 'Persistent Silica: Why Non-Degradable Glass Endangers Wildlife',
      snippet: 'Glass fragments left in natural environments do not decompose; instead, they act as optical lenses that start brushfires and cause severe lacerations to wildlife.',
      category: 'Glass',
      urgency: 'NON-DEGRADABLE',
      accentColor: '#0288d1',
      source: 'Wildlife Conservation Board',
      link: 'https://www.sciencedaily.com',
    },
  ];
}