import { supabase } from './supabase.js';

/**
 * Standardized fallback list of all 15 verified Recovery Hubs from Supabase markers table.
 * Ensures zero-delay instant rendering on startup and offline resilience.
 */
export const DEFAULT_RECOVERY_HUBS = [
  {
    id: 'ngo-4',
    rawId: '4',
    name: 'Greenciti',
    title: 'Greenciti',
    shortName: 'Greenciti',
    type: 'NGO',
    isNgo: true,
    address: '19, Dreams Mall, Near Bhandup Railway Station, L.B.S. Marg, Bhandup West, Mumbai – 400078',
    fullAddress: '19, Dreams Mall, Near Bhandup Railway Station, L.B.S. Marg, Bhandup West, Mumbai, Maharashtra 400078',
    latitude: 19.1458,
    longitude: 72.937,
    phone: '8097479747',
    website: 'https://www.greenciti.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 09:00 – 20:00',
    opening_hours: '09:00',
    closing_hours: '20:00',
    guidelines: 'Rinse and dry plastic/metal scrap. Keep e-waste devices segregated from cardboard and paper.',
    streams: ['plastic', 'metal', 'e-waste devices', 'cardboard and paper', 'fabric', 'organic'],
  },
  {
    id: 'ngo-5',
    rawId: '5',
    name: 'Saahas',
    title: 'Saahas',
    shortName: 'Saahas',
    type: 'NGO',
    isNgo: true,
    address: '#21, Ground Floor, MCHS Colony, 5th C Cross, 16th Main, BTM Layout 2nd Stage, Bengaluru – 560076',
    fullAddress: '#21, Ground Floor, MCHS Colony, 5th C Cross, 16th Main, BTM Layout 2nd Stage, Bengaluru, Karnataka 560076',
    latitude: 12.9166,
    longitude: 77.6101,
    phone: '080-41689889',
    website: 'https://saahas.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 09:00 – 17:00',
    opening_hours: '09:00',
    closing_hours: '17:00',
    guidelines: 'Clean, dry and segregated recyclables accepted. Separate hazardous electronic scrap from dry streams.',
    streams: ['plastic', 'metal', 'glass', 'e-waste devices', 'cardboard and paper', 'fabric', 'furniture', 'organic', 'rubber', 'other'],
  },
  {
    id: 'ngo-6',
    rawId: '6',
    name: 'Green Communities Foundation',
    title: 'Green Communities Foundation',
    shortName: 'Green Communities',
    type: 'NGO',
    isNgo: true,
    address: '58,484, Khandan Galli, off Swami Vivekanand Road, Siddharth Nagar 4, Jawahar Nagar, Goregaon West, Mumbai, Maharashtra 400104',
    fullAddress: '58,484, Khandan Galli, off Swami Vivekanand Road, Siddharth Nagar 4, Jawahar Nagar, Goregaon West, Mumbai, Maharashtra 400104',
    latitude: 19.1585,
    longitude: 72.8427,
    phone: '91 9137253765',
    website: 'https://www.greencf.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 09:30 – 18:00',
    opening_hours: '09:30',
    closing_hours: '18:00',
    guidelines: 'Clean, dry and segregated recyclables accepted.',
    streams: ['cardboard and paper', 'plastic', 'glass', 'organic'],
  },
  {
    id: 'ngo-7',
    rawId: '7',
    name: 'Green Yatra',
    title: 'Green Yatra',
    shortName: 'Green Yatra',
    type: 'NGO',
    isNgo: true,
    address: '308, EcoStar, Vishveshwar Nagar Rd, Churi Wadi, Goregaon East, Mumbai, Maharashtra 400063',
    fullAddress: '308, EcoStar, Vishveshwar Nagar Rd, Churi Wadi, Goregaon East, Mumbai, Maharashtra 400063',
    latitude: 19.1616,
    longitude: 72.8587,
    phone: '91 99675 38049',
    website: 'https://www.greenyatra.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 10:00 – 18:30',
    opening_hours: '10:00',
    closing_hours: '18:30',
    guidelines: 'Segregate dry recyclables and organic waste.',
    streams: ['cardboard and paper', 'plastic', 'glass', 'organic'],
  },
  {
    id: 'ngo-8',
    rawId: '8',
    name: 'Earth5R',
    title: 'Earth5R',
    shortName: 'Earth5R',
    type: 'NGO',
    isNgo: true,
    address: '128-A, Ground Floor, Reva Fort Colony, Sant Rohidas Marg, Kranti Nagar, Kala Killa, Dharavi, Mumbai, Maharashtra 400017',
    fullAddress: '128-A, Ground Floor, Reva Fort Colony, Sant Rohidas Marg, Kranti Nagar, Kala Killa, Dharavi, Mumbai, Maharashtra 400017',
    latitude: 19.0407,
    longitude: 72.8538,
    phone: '91 99200 45587',
    website: 'https://earth5r.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 09:30 – 18:00',
    opening_hours: '09:30',
    closing_hours: '18:00',
    guidelines: 'Drop off clean plastic, paper, and reusable fabric scrap.',
    streams: ['plastic', 'paper', 'fabric'],
  },
  {
    id: 'ngo-9',
    rawId: '9',
    name: 'Chintan',
    title: 'Chintan',
    shortName: 'Chintan',
    type: 'NGO',
    isNgo: true,
    address: 'C-14, Second Floor, Block C, Lajpat Nagar III, New Delhi, Delhi 110024',
    fullAddress: 'C-14, Second Floor, Block C, Lajpat Nagar III, New Delhi, Delhi 110024',
    latitude: 28.5696,
    longitude: 77.2375,
    phone: '91 11 4657 4171',
    website: 'https://www.chintan-india.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: 'Daily: 10:00 – 18:00',
    opening_hours: '10:00',
    closing_hours: '18:00',
    guidelines: 'Segregate dry waste and compostable organic scrap.',
    streams: ['paper', 'plastic', 'glass', 'fabric', 'organic'],
  },
  {
    id: 'ngo-10',
    rawId: '10',
    name: 'Recycle India Foundation',
    title: 'Recycle India Foundation',
    shortName: 'Recycle India',
    type: 'NGO',
    isNgo: true,
    address: 'National Recycler Network & Doorstep E-waste Collection, Mumbai & Pan-India',
    fullAddress: 'National Recycler Network & Doorstep E-waste Collection, Mumbai & Pan-India',
    latitude: 19.148,
    longitude: 72.936,
    phone: '91 62915 59908',
    website: 'https://recycleindiafoundation.com',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Doorstep E-Waste & Plastic Recovery Service',
    timings: 'Daily: 09:00 – 17:00',
    opening_hours: '09:00',
    closing_hours: '17:00',
    guidelines: 'Schedule doorstep pickup for bulky electronics or plastic bulk scrap.',
    streams: ['e-waste devices', 'plastic'],
  },
  {
    id: 'ngo-11',
    rawId: '11',
    name: 'Goonj',
    title: 'Goonj',
    shortName: 'Goonj',
    type: 'NGO',
    isNgo: true,
    address: 'Gala No. 6 B, Raju Industrial Estate, Penkar Pada Road, Near Dahisar Check Naka, Mira Road East, Thane – 401104',
    fullAddress: 'Gala No. 6 B, Raju Industrial Estate Premises Co-operative Society Ltd., Penkar Pada Road, Near Dahisar Check Naka, Mira Road East, Thane – 401104',
    latitude: 19.2815,
    longitude: 72.8697,
    phone: '1800 202 9012',
    website: 'https://goonj.org/dropping-centres',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Material Recovery & Upcycling Center',
    timings: 'Daily: 10:00 – 17:00',
    opening_hours: '10:00',
    closing_hours: '17:00',
    guidelines: 'Accepts wearable clothes, usable textiles, and intact furniture.',
    streams: ['fabric', 'furniture'],
  },
  {
    id: 'ngo-12',
    rawId: '12',
    name: 'Karo Sambhav',
    title: 'Karo Sambhav',
    shortName: 'Karo Sambhav',
    type: 'NGO',
    isNgo: true,
    address: 'Gala No. 6 & 7, Near Home Guard Training Centre, NSS Road, Ghatkopar West, Mumbai – 400084',
    fullAddress: 'Gala No. 6 & 7, Near Home Guard Training Centre, NSS Road, Near Umar Medical, Ghatkopar West, Mumbai – 400084',
    latitude: 19.086,
    longitude: 72.9081,
    phone: '91 92892 36008',
    website: 'https://www.karosambhav.com/collection-centres',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Authorized E-Waste & Recyclables Drop-off',
    timings: 'Daily: 09:30 – 18:00',
    opening_hours: '09:30',
    closing_hours: '18:00',
    guidelines: 'Drop off end-of-life laptops, batteries, electronic items, and glass containers.',
    streams: ['e-waste devices', 'plastic', 'glass'],
  },
  {
    id: 'ngo-13',
    rawId: '13',
    name: 'MumbaiScrap',
    title: 'MumbaiScrap',
    shortName: 'MumbaiScrap',
    type: 'NGO',
    isNgo: true,
    address: 'Ram Mandir Road, Goregaon West, Mumbai, Maharashtra 400104',
    fullAddress: 'Ram Mandir Road, Goregaon West, Mumbai, Maharashtra 400104',
    latitude: 19.1555,
    longitude: 72.85,
    phone: '91 80806 96004',
    website: 'https://www.mumbaiscrap.in',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Urban Scrap & Material Recovery Station',
    timings: 'Daily: 09:00 – 22:00',
    opening_hours: '09:00',
    closing_hours: '22:00',
    guidelines: 'Accepts scrap metals, discarded appliances, paper bundles, and plastics.',
    streams: ['metal', 'furniture', 'e-waste', 'plastic', 'paper'],
  },
  {
    id: 'ngo-14',
    rawId: '14',
    name: 'Project Mumbai',
    title: 'Project Mumbai',
    shortName: 'Project Mumbai',
    type: 'NGO',
    isNgo: true,
    address: '205, 2nd Floor, Eco Heights, Nityanand Society, Sahar Road, Andheri East, Mumbai 400069',
    fullAddress: '205, 2nd Floor, Eco Heights, Nityanand Society, Sahar Road, Andheri East, Mumbai 400069',
    latitude: 19.1187,
    longitude: 72.863,
    phone: '91 96533 30712',
    website: 'https://respunindia.com',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Citizen Plastic & E-waste Recycling Hub',
    timings: 'Daily: 10:00 – 17:00',
    opening_hours: '10:00',
    closing_hours: '17:00',
    guidelines: 'Clean and dry segregated plastic packaging and household e-waste.',
    streams: ['plastic', 'e-waste devices'],
  },
  {
    id: 'ngo-15',
    rawId: '15',
    name: 'Stree Mukti Sanghatana',
    title: 'Stree Mukti Sanghatana',
    shortName: 'Stree Mukti',
    type: 'NGO',
    isNgo: true,
    address: '31, Shramik (Royal Crest), Lokmanya Tilak Colony Road No. 3, Dadar East, Mumbai 400014',
    fullAddress: '31, Shramik (Royal Crest), Lokmanya Tilak Colony Road No. 3, Dadar East, Mumbai 400014',
    latitude: 19.0178,
    longitude: 72.8478,
    phone: '022-24174381',
    website: 'https://streemuktisanghatana.org',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Organic Waste & Composting Center',
    timings: 'Daily: 11:30 – 18:30',
    opening_hours: '11:30',
    closing_hours: '18:30',
    guidelines: 'Accepts segregated wet waste, garden clippings, and organic kitchen waste for composting.',
    streams: ['organic'],
  },
  {
    id: 'ngo-16',
    rawId: '16',
    name: 'Waste Matters Foundation',
    title: 'Waste Matters Foundation',
    shortName: 'Waste Matters',
    type: 'NGO',
    isNgo: true,
    address: '121, National Storage Building, S.B. Road, Mahim West, Mumbai 400016',
    fullAddress: '121, National Storage Building, S.B. Road, Mahim West, Mumbai 400016',
    latitude: 19.034,
    longitude: 72.842,
    phone: '',
    website: 'https://wastematters.org.in',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Plastic Upcycling & Recovery Center',
    timings: 'Daily: 09:30 – 18:30',
    opening_hours: '09:30',
    closing_hours: '18:30',
    guidelines: 'Accepts all rigid and flexible recyclable consumer plastics.',
    streams: ['plastic'],
  },
  {
    id: 'ngo-17',
    rawId: '17',
    name: 'Plastoconomy Foundation',
    title: 'Plastoconomy Foundation',
    shortName: 'Plastoconomy',
    type: 'NGO',
    isNgo: true,
    address: 'Gala No. 01, Rambaug Upvan, Pokharan Road No. 2, Thane West, Maharashtra 400610',
    fullAddress: 'Gala No. 01, Rambaug Upvan, Pokharan Road No. 2, Thane West, Maharashtra 400610',
    latitude: 19.2183,
    longitude: 72.9781,
    phone: '91 89767 98272',
    website: 'https://www.plastoconomyfoundation.co.in',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Circular Plastic Collection Hub',
    timings: 'Daily: 09:00 – 21:00',
    opening_hours: '09:00',
    closing_hours: '21:00',
    guidelines: 'Drop off bottles, caps, packaging, and hard plastics.',
    streams: ['plastic'],
  },
  {
    id: 'ngo-18',
    rawId: '18',
    name: "Tisser Artisan's Trust",
    title: "Tisser Artisan's Trust",
    shortName: 'Tisser Artisans',
    type: 'NGO',
    isNgo: true,
    address: 'A,2-117, 1st Floor, BGTA Nilgiri Building, Wadala Truck Terminus, Near RTO Training Ground, Mumbai 400037',
    fullAddress: 'A,2-117, 1st Floor, BGTA Nilgiri Building, Wadala Truck Terminus, Near RTO Training Ground, Mumbai 400037',
    latitude: 19.022,
    longitude: 72.872,
    phone: '8104047525',
    website: 'https://tisser.in/donation',
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Textile Upcycling & Artisan Craft Center',
    timings: 'Daily: 11:00 – 18:30',
    opening_hours: '11:00',
    closing_hours: '18:30',
    guidelines: 'Accepts clean scrap fabrics, surplus textiles, and cotton scraps for upcycling.',
    streams: ['fabric'],
  },
];

/**
 * Cleanly format a raw row from Supabase 'markers' table into a unified Hub object.
 */
export function formatHubRecord(item, index) {
  const rawName = item.name || 'Recovery Hub';
  // Clean underscore separators (e.g. Green_Communities_Foundation -> Green Communities Foundation)
  const cleanName = rawName.replace(/_/g, ' ').trim();
  const displayName = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);

  // Normalize URL formatting (handles "https:,,site.org," or broken commas)
  let websiteUrl = item.website || '';
  if (websiteUrl) {
    websiteUrl = websiteUrl.replace(/,/g, '/').replace(/\/+/g, '/').replace('https:/', 'https://');
    if (websiteUrl.endsWith('/')) websiteUrl = websiteUrl.slice(0, -1);
  }

  // Clean accepted streams (removes trailing semicolons and trims each tag)
  const streams = typeof item.type_of_trash === 'string'
    ? item.type_of_trash
        .replace(/;/g, '')
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
    : ['general recyclable scrap'];

  // Safe coordinates with fallback
  const lat = item.latitude != null ? parseFloat(item.latitude) : 19.148;
  const lon = item.longitude != null ? parseFloat(item.longitude) : 72.936;

  const rawId = item.id != null ? item.id.toString() : index.toString();
  const address = item.address || 'Mumbai Network (Pickup & Drop-off)';

  return {
    id: `ngo-${rawId}`,
    rawId: rawId,
    name: displayName,
    title: displayName,
    shortName: displayName.length > 20 ? displayName.substring(0, 18) + '...' : displayName,
    type: item.type ? item.type.trim() : 'NGO',
    isNgo: true,
    address: address,
    fullAddress: address,
    latitude: lat,
    longitude: lon,
    phone: item.phone ? item.phone.toString().trim() : '',
    website: websiteUrl,
    status: 'Recovery Hub',
    statusColor: '#166534',
    icon: 'business',
    color: '#166534',
    facilityType: 'Community Material Recovery & Drop-off Hub',
    timings: item.opening_hours && item.closing_hours
      ? `Daily: ${item.opening_hours} – ${item.closing_hours}`
      : 'Mon – Sat: 9:30 AM – 6:00 PM',
    opening_hours: item.opening_hours || '09:30',
    closing_hours: item.closing_hours || '18:00',
    guidelines: 'Clean, dry and segregated recyclables accepted.',
    streams: streams.length > 0 ? streams : ['plastic', 'dry waste'],
  };
}

/**
 * Fetch all recovery hubs dynamically from Supabase 'markers' table,
 * falling back gracefully to DEFAULT_RECOVERY_HUBS if network fails.
 */
export async function fetchRecoveryHubs() {
  try {
    const { data, error } = await supabase.from('markers').select('*');
    if (error) {
      console.warn('Supabase markers query warning:', error.message);
      return DEFAULT_RECOVERY_HUBS;
    }
    if (data && data.length > 0) {
      const formatted = data.map((item, idx) => formatHubRecord(item, idx));
      return formatted;
    }
  } catch (err) {
    console.warn('Error fetching recovery hubs from Supabase:', err?.message || err);
  }
  return DEFAULT_RECOVERY_HUBS;
}
